// Code generated by "stringer -type=Status"; DO NOT EDIT

package nexmo

import "fmt"

const (
	_Status_name_0 = "StatusSuccessStatusBusy"
	_Status_name_1 = "StatusInvalidStatusInvalidCredentialsStatusInternalError"
	_Status_name_2 = "StatusPartnerQuotaExceeded"
	_Status_name_3 = "StatusFacilityNotAllowed"
	_Status_name_4 = "StatusUnparseable"
)

var (
	_Status_index_0 = [...]uint8{0, 13, 23}
	_Status_index_1 = [...]uint8{0, 13, 37, 56}
	_Status_index_2 = [...]uint8{0, 26}
	_Status_index_3 = [...]uint8{0, 24}
	_Status_index_4 = [...]uint8{0, 17}
)

func (i Status) String() string {
	switch {
	case 0 <= i && i <= 1:
		return _Status_name_0[_Status_index_0[i]:_Status_index_0[i+1]]
	case 3 <= i && i <= 5:
		i -= 3
		return _Status_name_1[_Status_index_1[i]:_Status_index_1[i+1]]
	case i == 9:
		return _Status_name_2
	case i == 19:
		return _Status_name_3
	case i == 999:
		return _Status_name_4
	default:
		return fmt.Sprintf("Status(%d)", i)
	}
}
